### ISSUE TITLE
Что то пошло не так

### ISSUE THREAD

**Issue by maxyc** [technoeleganceteam/kanban_on_rails#3]
ЗАрегистрировался через битбакет. 
Создал проект nextrun
добавил 2 задачи. но я их нигде не вижу. 
в списке слева напротив проекта (2) стоит. но больше нигде. линукс минт. хром.

**Comment by gkopylov** [comment]
Для того, чтобы их увидеть, в проекте вам нужно добавить столбец с каким-нибудь тегом(или тегами) и раздел/разделы(можно с какими-нибудь тегами или просто поставить галку в чекбоксе "Или включать всё"). Затем отредактировать ваши импортированные issues'ы добавив к ним соответсвующие теги(это можно сделать кликнув по кнопке "Задачи проекта" напротив названия проекта). После этого вы увидете вашу Канбан доску с карточками.

В Битбакете сейчас, к сожалению, теги(лейблы) до сих пор не добавлены https://bitbucket.org/site/master/issues/5356/labels-for-issues-bb-6550 но как раз в моём сервисе вы можете их добавлять/редактировать и получить такую, скажем, "надстройку" над issues'ами в Битбакете.

Спасибо за использование сервиса, мне приятно что он приносит пользу. Я постараюсь сделать более продуманный интерфейс, чтобы пользователю было удобней редактировать задачи и обновлять проект.
