### ISSUE TITLE
Add backlog column

### ISSUE THREAD

**Issue by gkopylov** [technoeleganceteam/kanban_on_rails#8]
Add backlog column with issues which tags is not present(overlapping) in other columns.

**Comment by lokson** [comment]
Hi, I'm confused by a "Ready to work" label. Does it mean that this feature is written but not pushed yet?

**Comment by gkopylov** [comment]
It means that I definitely do this feature soon.

Thank for your interest :-)

**Comment by gkopylov** [comment]
Finish to work with this feature. Now it is available in the production.

Backlog column can be set with checkbox "Backlog" and cannot contain any tags. Simple column(not "Backlog") should contain at least one tag.

**Comment by lokson** [comment]
Thanks!
