### ISSUE TITLE
How to place issue on board

### ISSUE THREAD

**Issue by lokson** [technoeleganceteam/kanban_on_rails#9]
Hi, 

How to place issue on board? On my account an issue is created and a board too and they both belong to the same project.

**Comment by gkopylov** [comment]
You need to create columns and sections for your board. If any columns or sections will contain tags that overlapping with issues tags then issue will appear there. For example, you can create section with "Include all tags" and few columns with tags "Testing", "Developing" and "Design". Then if you create issue with tag/label "Design" it will appear in column with tag "Design". You can move this issue later to different columns and its tags will change accordingly.

I will add section about this and how KanbanOnRails works in the README.md soon.

**Comment by lokson** [comment]
Thanks for reply.

Here is solo project with one issue.

![screen shot 2016-06-18 at 23 10 57](https://cloud.githubusercontent.com/assets/5403694/16173733/fc749bee-35aa-11e6-8fee-225161c01bc8.png)

Issue has a 'backlog' tag.

![screen shot 2016-06-18 at 23 12 06](https://cloud.githubusercontent.com/assets/5403694/16173737/2b22b642-35ab-11e6-8f7d-455403745fe0.png)

And a board has a column defined with that tag.

![screen shot 2016-06-18 at 23 12 51](https://cloud.githubusercontent.com/assets/5403694/16173749/807c9784-35ab-11e6-8c02-bebd9c1e4dea.png)

But the column seems to be empty.

![screen shot 2016-06-18 at 23 22 59](https://cloud.githubusercontent.com/assets/5403694/16173754/bc34eff6-35ab-11e6-8ce8-a4df29f625f0.png)

**Comment by gkopylov** [comment]
@lokson thank you for your reporting :+1: 

Yes, there was an issue when you creating a board, now I fix it and everything should work fine. Happy product management :-)
